---
container_state: running
setenforce: false

container_name: pihole
container_image: pihole/pihole:latest
container_dir_config: pihole-etc
container_dir_data: pihole-dnsmasq.d
container_dir_owner: 0
container_dir_group: 0
container_run_args: >-
  -d
  -p 53:53/tcp
  -p 53:53/udp
  -p 67:67/udp
  -p 80:80/tcp
  -p 443:443/tcp
  -v "{{podman_exported_container_volumes_basedir}}/{{container_dir_config}}:/etc/pihole:Z"
  -v "{{podman_exported_container_volumes_basedir}}/{{container_dir_data}}:/etc/dnsmasq.d:Z"
  --hostname="pihole.{{ domain }}"
  --memory=512M
  -e "TZ={{ timezone }}"
  --dns 127.0.0.1,192.168.117.1
firewall_port_list:
  - 53:53/tcp
  - 53:53/udp
  - 67:67/udp
  - 80:80/tcp
  - 443:443/tcp
## goes to host_vars ##
# podman_exported_container_volumes_basedir: /var/lib/containers/exported_volumes
# domain: localdomain
# timezone: "Europe/Helsinki"