---
- name: Install WireGuard
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    # - linux-headers-{{ ansible_kernel }}
    # - wireguard-dkms
    - wireguard-tools
  tags:
    - wg-install

# - name: Reboot when centos
#   reboot:
#   when: ansible_os_family == "RedHat"
  

# - name: Enable WireGuard kernel module
#   modprobe:
#     name: wireguard
#     state: present
#   register: wireguard_module_enabled
#   until:  wireguard_module_enabled is succeeded
#   retries: 10
#   delay: 10
#   failed_when: wireguard_module_enabled is failure
#   tags:
#     - wg-install

