---
# - name: configurable backup path
#   ios_config:
#     src: ios_template.j2
#     backup: yes
#     backup_options:
#       filename: backup.cfg
#       dir_path: /home/user


# - name: configure ip helpers on multiple interfaces
#   ios_config:
#     lines:
#       - ip helper-address 172.26.1.10
#       - ip helper-address 172.26.3.8
#     parents: "{{ item }}"
#   with_items:
#     - interface Ethernet1
#     - interface Ethernet2
#     - interface GigabitEthernet1


# - name: configure interface settings
#   ios_config:
#     lines:
#       - description test interface
#       - ip address 172.31.1.1 255.255.255.0
#     parents: interface Ethernet1

- name: run multiple commands on remote nodes
  ios_command:
    commands:
      - show version
      - show interfaces