---
container_state: running
setenforce: false

### Example varibles ###
# container_name: hassio
# container_image: docker.io/homeassistant/home-assistant:latest
# container_dir_owner: root
# container_dir_group: root
# container_dir_config: config
# container_add_cmd_0: ## if you need to run additional cmds proir to running the container. You have to place these in the podman_container_systemd task/main.yml. Any subseqental additional cmd use the first one as a template and label by number.
# container_add_cmd_1: ## if you need to run additional cmds proir to running the container. You have to place these in the podman_container_systemd task/main.yml. Any subseqental additional cmd use the first one as a template and label by number.
# container_dir_ssl: ssl
# container_run_args: >-
#   -dt
#   -v "{{podman_exported_container_volumes_basedir}}/{{ container_dir_config }}:/config:Z"
#   -v "{{podman_exported_container_volumes_basedir}}/{{ container_dir_ssl }}:/ssl:Z"
#   -v /etc/localtime:/etc/localtime:z
#   -e "TZ={{ timezone }}"
#   --net=host
# database_run_args: >-
#   -d
#   -p 8086:8086
#   -v "{{podman_exported_container_volumes_basedir}}/{{ container_dir_config }}:/etc/influxdb:Z"
#   -v "{{podman_exported_container_volumes_basedir}}/{{ container_dir_db }}:/var/lib/influxdb:Z"
#   --net=host
# database_initialize_args: >-
#   -e INFLUXDB_DB="{{ influx_database_name }}" 
#   -e INFLUXDB_ADMIN_ENABLED=true
#   -e INFLUXDB_ADMIN_USER=admin 
#   -e INFLUXDB_ADMIN_PASSWORD="{{ influx_database_admin_pass }}"
#   -e INFLUXDB_USER="{{ influx_database_user }}"
#   -e INFLUXDB_USER_PASSWORD="{{ influx_database_user_pass }}"
#   -v "{{ podman_exported_container_volumes_basedir }}/{{ container_dir_db }}:/var/lib/influxdb:Z"
# container_firewall_ports:
#   - 8123/tcp 

## goes to group_vars ##
# podman_exported_container_volumes_basedir: /var/lib/containers/exported_volumes
# domain: localdomain
# timezone: "Europe/Helsinki"