---
# defaults file for wireguard_role

#Declare the VPN subnet
vpn_network: '10.200.200'

#Declare the VPN server port
vpn_port: '51820'

#Declare the number of clients
clients: 3

client_config_path: '~/Desktop/wireguard_role/profiles'

wireguard_nat: true
wireguard_dns: false