---
pod_name: example
pod_label: example
pod_yaml_dir: /etc/containers/pods
pod_yaml_file: "{{ pod_name }}.yaml"
pod_yaml_path: "{{ pod_yaml_dir }}/{{ pod_yaml_file }}"

pod_container_image_list:
  - "docker.io/library/postgres:{{ awx_postgres_version }} "
  - "docker.io/library/memcached:alpine"
  - "docker.io/ansible/awx_rabbitmq:{{ awx_rabbitmq_version }}"
  - "docker.io/ansible/awx_web:{{ awx_awxweb_version }}"
  - "docker.io/ansible/awx_task:{{ awx_awxtask_version }}"





### pod specific defaults
awx_admin_user: admin
awx_admin_password: password
#
# anything below is pod internal info, never seen outside.
#
awx_postgres_user: awx
awx_postgres_password: awxpass

awx_rabbitmq_user:  guest
awx_rabbitmq_password: awxrabbit
awx_rabbitmq_secret_key: awxsecret
awx_rabbitmq_erlang_cookie: cookiemonster

awx_awxweb_version: 3.0.1
awx_awxtask_version: 3.0.1
awx_postgres_version: 9.6
awx_rabbitmq_version: 3.7.4

