---
- hosts: proxmaox
  gather_facts: yes
  become: yes
  vars:
  tasks:

    - name: Set a random vmid when vmnewid is not defined
      set_fact:
        value: "{{ 3000 | random(start=2000) }}"
      register: random_id
      # when: vmnewid

    - name: Set a random vmid when vmnewid is not defined
      set_fact:
        value: "devops.{{ 100000 | random }}.{{ domain }}"
      register: random_name
      when: vmname is not defined