---
- hosts: proxmox
  gather_facts: yes
  become: true
  vars:
    ## -- Container vars -- ##
    action      : start
    ctid        : 247 # Varible has to be set in playbook
    ctpassword  : lukmanlab # Varible has to be set in playbook
    ctip        : 172.16.1.183/24
    ctgw        : 172.16.1.1
    ctbridge    : vmbr0
    OS_Template : centos-7-default_20171212_amd64.tar.xz
    # ubuntu-18.04-standard_18.04-1_amd64.tar.gz 
    # ubuntu-16.04-standard_16.04-1_amd64.tar.gz 
    # centos-7-default_20171212_amd64.tar.xz
  roles:
  - role: ansible_role_proxmox

## -- If you want multiple containers provisioned -- ##
# - hosts: proxmox
#   gather_facts: yes
#   vars:
#     ## -- Container vars -- ##
#     action      : start
#     ctid        : 243 # Varible has to be set in playbook
#     ctpassword  : lukmanlab # Varible has to be set in playbook
#     OS_Template : centos-7-default_20171212_amd64.tar.xz
#     # ubuntu-18.04-standard_18.04-1_amd64.tar.gz 
#     # ubuntu-16.04-standard_16.04-1_amd64.tar.gz 
#     # centos-7-default_20171212_amd64.tar.xz
#   roles:
#   - role: container



## -- Additional vars -- ##
# cthostname  : server.vanguard.local
# searchdomain: vanguard.local
# ctnameserver: 8.8.8.8
# ctcores     : 2
# ctmemory    : 1024
# ctswap      : 512
# ctdisk      : 8
# ctstorage   : local-lvm
# ctnetif     : 
#   net0: "name=eth0,ip=dhcp,bridge=vmbr0"
  # net0: "name=eth0,ip=8.8.8.8,gw=9.9.9.9,bridge=vmbr0"
# ctmounts    : 
#   mp0: "/mnt/pve/cephfs_data/downloads/,mp=/downloads"
#   mp1: "/mnt/pve/cephfs_data/media,mp=/media"
# ctunprivileged: yes
# ctpubkey    : "ssh-rsa myPublicKey engonzal@hostname"
# ctonboot    : no

