---
- name: reload prosody config
  service:
    name: prosody
    state: reloaded

- name: restart prosody
  service:
    name: prosody
    state: restarted

- name: restart munin-node
  service:
    name: munin-node
    state: restarted

- name: restart monit
  service:
    name: monit
    state: restarted

- name: restart saslauthd
  service:
    name: saslauthd
    state: restarted
