---
# - name: waiting the host terminate the clone
#   wait_for:
#     timeout: 20

- name: Test in access host
  ping:

- name: "Create {{ vmname | default(random_name) }}"
  command: qm create "{{ vmnewid | default(random_id) }}" --name "{{ vmname | default(random_name) }}" --memory "{{ vmmemory | default(omit) }}" --net0 virtio,bridge="{{ vmbridge | default(omit) }}" --cores "{{ vmcores | default(omit) }}" --sockets "{{ vmsockets | default(omit) }}"
# ,tag="{{ vmvlan | default(omit) }}"
  # qm create 3289 --name devop.3289.vanguard.local --memory 4096 --net0 '{"net0":"virtio,bridge={{ vmbridge | default(omit) }},tag={{ vmvlan | default(omit) }}"}' --cores "{{ vmcores | default(omit) }}" --sockets "{{ vmsockets | default(omit) }}"


- name: Import disk
  command: qm importdisk "{{ vmnewid | default(random_id) }}" "{{ proxmox_cloud_img }}" "/mnt/smb/template/iso/{{ vmstorage | default(omit) }}"

- name: Set QEMU agent
  command: qm set "{{ vmnewid | default(random_id) }}" --agent 1

# - name: Applying resizing in the disk
#   command: qm resize "{{ vmnewid }}" scsi0 "{{ vmdisk |default(omit) }}"
# sshkey only works if you use a file. You must use it
- name: Create cloudinit rom
  command: qm set "{{ vmnewid | default(random_id) }}" --ide2 "{{ vmstorage | default(omit) }}":cloudinit

- name: Settinging the user and nameserver in Cloud Init
  command: qm set "{{ vmnewid | default(random_id) }}" --searchdomain "{{ vmsearchdomain | default(omit) }}" --nameserver "{{ vmnameserver | default(omit) }}" --ciuser "{{ ciuser | default(omit) }}" --cipassword "{{ cipassword | default(omit) }}" --sshkey "/root/.ssh/{{ sshkey | default(omit) }}"

# - name: Settinging the newtork in host
#   command: qm set "{{ vmnewid | default(random_id) }}" --net0 model=virtio,bridge="{{ vmbridge | default(omit) }}"
  # ,macaddr="{{ vmmacaddr | default(omit) }}"

- name: Settinging the newtork in Cloud Init
  command: qm set "{{ vmnewid | default(random_id) }}" --ipconfig0 ip="{{ vmip | default(omit) }}",gw="{{ vmgw | default(omit) }}"
  when: 
  - vmip is defined
