---
- name: ensure "{{ container_name }}" container files mount point on host
  tags: mount
  file:
    path: "{{podman_exported_container_volumes_basedir}}/{{ item }}"
    owner: "{{ container_dir_owner }}"
    group: "{{ container_dir_group }}"
    state: directory
    recurse: yes
  with_items:
    - "{{ container_dir_proc }}"
    - "{{ container_dir_sys }}"

- name: ensure "{{ container_name }}" container state
  tags: container
  import_role:
    name: podman_container_systemd
