---
- name: Adding dnsrecord
  ipa_dnsrecord:
    zone_name: "{{ zone_name }}"
    record_name: '{{ hostname }}'
    record_type: "{{ record_type | default('A') }}"
    record_value: '{{ ip_address }}'
    ipa_host: "{{ freeipa_host }}"
    ipa_user: "{{ freeipa_user }}"
    ipa_pass: "{{ freeipa_pass }}"
    state: present

    
# - name: Ensure host is present
#   ipa_host:
#     name: "{{ hostname }}.{{ zone_name }}"
#     description: "{{ description | default(omit) }}"
#     # ip_address: "{{ ip_address }}"
#     ns_host_location: "{{ ns_host_location | default(omit) }}"
#     ns_os_version: "{{ ns_os_version | default(omit) }}"
#     ns_hardware_platform: "{{ ns_hardware_platform | default(omit) }}"
#     # mac_address:
#     # - "08:00:27:E3:B1:2D"
#     ipa_host: "{{ freeipa_host }}"
#     ipa_user: "{{ freeipa_user }}"
#     ipa_pass: "{{ freeipa_pass }}"
#     state: present
    

