---
- name: Installing takserver
  hosts: takserver
  # remote_user: root
  become: yes
  # become_method: sudo
  # vars:
  #   version: 1.3.12-RELEASE6
  #   password_takadmin: atakatak
  #   user_webadmin: admin
  #   password_webadmin: atakatak
  #   admincert: webAdmin0
  #   name_takclients:
  #     - admin0
  #     - webAdmin0
  #     # - webAdmin1
  #     # - jed0
  #     # - jed1
  #     # - jed2
  #     # - jed3
  #     # - jed4
  #     # - jed5
  #   additional_packages: 
  #     - vim
  #     - htop
  #   firewall_ports:
  #     - '8087/tcp'
  #     - '8087/udp'
  #     - '8089/tcp'
  #     - '8080/tcp'
  #     - '8443/tcp'
  #     # - '5432/tcp'
  roles:
    - takserver
