---
- name: restart iptables
  service:
    name: iptables
    state: restarted

- name: restart firewalld
  service:
    name: firewalld
    state: restarted

- name: restart ufw
  service:
    name: ufw
    state: restarted

- name: save iptables rules (Debian/Ubuntu and CentOS/RHEL/Fedora)
  shell: "{{ iptables_save_command }}"
  when: ansible_os_family == 'Debian' or ansible_os_family == 'RedHat' or ansible_os_family == 'CentOS'
  listen: "save iptables"
