---
- name: Check if certs and keys exist
  stat:
    path: "{{ dir_ssl_key }}"
  register: cert_stat_result

- name: mkdir ssl directory
  file:
    path: "{{ dir_ssl_key }}/{{ item }}" 
    mode: 0775
    state: directory
  with_items: '{{ servers }}'
  when: cert_stat_result

- name: Generate self signed certificate
  command: openssl req  -new -newkey rsa:4096 -x509 -sha256 -days 365 -nodes -out "{{ dir_ssl_key }}/{{ item }}"/cert.pem -keyout "{{ dir_ssl_key }}/{{ item }}"/key.pem -subj "/C={{ name_country }}/ST={{ name_state }}/L={{ name_city }}/O={{ name_company }}/CN={{ item }}.{{ name_common }}"
  become: yes
  with_items: '{{ servers }}'
  when: cert_stat_result


- name: change permissions
  file:
    path: "{{ dir_ssl_key }}/{{ item }}/key.pem" 
    mode: 0400
  with_items:
    - '{{ servers }}'
  when: cert_stat_result



# openssl req  -new -newkey rsa:4096 -x509 -sha256 -days 365 -nodes -out cert.crt -keyout key.key -subj "/C={{ name_country }}/ST={{ name_state }}/L={{ name_city }}/O={{ name_company }}/CN={{ name_common }}"


