---
- name: Add a new user
  user:
    name: "{{ item.username }}"
    groups: "{{ item.groups | default('') }}"
    password: "{{ init_setup_password | password_hash('sha512') }}"
    shell: /bin/bash
    update_password: on_create
  with_items:
    - "{{ init_setup_CentOS_users }}"
  when: ansible_facts['os_family'] == "RedHat"

- name: Require new users to reset password at login
  shell: passwd --expire "{{ item.username }}"
  with_items:
    - "{{ init_setup_CentOS_users }}"
  when: ansible_facts['os_family'] == "RedHat"

- name: "Allow admin users to sudo without a password"
  lineinfile:
    dest: "/etc/sudoers" # path: in version 2.3
    state: "present"
    regexp: "^%wheel"
    line: "%wheel ALL=(ALL) NOPASSWD: ALL"
  when: ansible_facts['os_family'] == "RedHat"

- name: Add a new user
  user:
    name: "{{ item.username }}"
    groups: "{{ item.groups | default('') }}"
    password: "{{ init_setup_password | password_hash('sha512') }}"
    shell: /bin/bash
    update_password: on_create
  with_items:
    - '{{ init_setup_Ubuntu_users }}'
  when: ansible_facts['os_family'] == "Debian"

- name: Require new users to reset password at login
  shell: passwd --expire "{{ item.username }}"
  with_items:
    - '{{ init_setup_Ubuntu_users }}'
  when: ansible_facts['os_family'] == "Debian"

- name: "Allow admin users to sudo without a password"
  lineinfile:
    dest: "/etc/sudoers" # path: in version 2.3
    state: "present"
    regexp: "^%sudo"
    line: "%sudo ALL=(ALL) NOPASSWD: ALL"
  when: ansible_facts['os_family'] == "Debian"
