---

- name: Determine domains to obtain certificates for (Nextcloud)
  set_fact:
    domains_to_obtain_certificate_for: "['{{ hostname_nextcloud }}']"

- name: Allow access to HTTP/HTTPS in firewalld
  firewalld:
    service: "{{ item }}"
    state: enabled
    immediate: yes
    permanent: yes
  with_items:
    - http
    - https
  when: ansible_os_family == 'RedHat'

- name: Ensure certbot Docker image is pulled
  docker_image:
    name: "{{ nextcloud_ssl_certbot_docker_image }}"

- name: Ensure SSL certificates path exists
  file:
    path: "{{ item }}"
    state: directory
    mode: 0770
    owner: "{{ nextcloud_user_username }}"
    group: "{{ nextcloud_user_username }}"
  with_items:
    - "{{ nextcloud_ssl_log_dir_path }}"
    - "{{ nextcloud_ssl_config_dir_path }}"

- name: Obtain initial certificates
  include_tasks: "setup_ssl_for_domain.yml"
  with_items: "{{ domains_to_obtain_certificate_for }}"
  loop_control:
    loop_var: domain_name

- name: Ensure SSL renewal script installed
  template:
    src: "{{ role_path }}/templates/usr-local-bin/nextcloud-ssl-certificates-renew.j2"
    dest: "/usr/local/bin/nextcloud-ssl-certificates-renew"
    mode: 0750

- name: Ensure periodic SSL renewal cronjob configured
  template:
    src: "{{ role_path }}/templates/cron.d/nextcloud-ssl-certificate-renewal.j2"
    dest: "/etc/cron.d/nextcloud-ssl-certificate-renewal"
    mode: 0600
