---
container_state: running
setenforce: false

container_name: openhab
container_image: openhab/openhab:2.3.0-amd64-alpine
container_dir_config: openhab_conf
container_dir_data: openhab_userdata
container_dir_addons: openhab_addons
container_dir_owner: 9001
container_dir_group: 9001
container_run_args: >-
  -d
  -p 8083:8080/tcp
  -p 8101:8101/tcp
  -p 5007:5007/tcp
  -v "{{podman_exported_container_volumes_basedir}}/{{container_dir_addons}}:/openhab/addons:Z"
  -v "{{podman_exported_container_volumes_basedir}}/{{container_dir_config}}:/openhab/conf:Z"
  -v "{{podman_exported_container_volumes_basedir}}/{{container_dir_data}}:/openhab/userdata:Z"
  --hostname="openhab.{{ domain }}"
  --memory=512M
  -e EXTRA_JAVA_OPTS="-Duser.timezone={{ timezone }}"
firewall_port_list:
  - 8083/tcp
  - 8101/tcp
  - 5007/tcp
## goes to host_vars ##
# podman_exported_container_volumes_basedir: /var/lib/containers/exported_volumes
# domain: localdomain
# timezone: "Europe/Helsinki"